### ISSUE TITLE
Compatibility with nc 23

### ISSUE THREAD

**Issue by exmerc** [PanCakeConnaisseur/user_backend_sql_raw#39] opened 2022-03-11 08:47 UTC
Hi bro

Do you have in your plans to make the module compatible with NC 23?

**Comment by 1358** [comment] 2022-03-22 11:15
it seems as if it is compatible as forcefully re-enabling it via `./occ app:enable user_backend_sql_raw --force` works fine now for a couple of weeks without any issues

**Comment by scchearn** [comment] 2022-05-05 03:52
Is this still the case? Forcefully enabling it? What needs to change for it to be seen as compatible?

**Comment by 1358** [comment] 2022-05-05 07:28
It is still working "fine" here with NC23.0.3

However I did not dig into details

**Comment by gpgmailencrypt** [comment] 2022-05-09 07:51
Technically it would be quite easy. The "max-version" entry in this file has to be updated
[https://github.com/PanCakeConnaisseur/user_backend_sql_raw/blob/7f23823d850578761082d3666f88b5793c7821f6/appinfo/info.xml#L34](https://github.com/PanCakeConnaisseur/user_backend_sql_raw/blob/7f23823d850578761082d3666f88b5793c7821f6/appinfo/info.xml#L34)
But this can only be done by the code owner

**Comment by PanCakeConnaisseur** [comment] 2022-05-29 15:43
Duplicate of #38

**Closed by PanCakeConnaisseur** 2022-05-29 15:43 UTC

**Comment by PanCakeConnaisseur** [comment] 2022-05-29 15:44
Since I have been applying all NC architecture changes immediately in the app, it will likely always work for several subsequent versions when you force its usage as someone suggested above.
